# -*- coding: utf-8 -*-
"""Automate the Boring Stuff with Python chap 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RFdm6XD7YSgflHrHNZVueBn-sCW4gYMm
"""

password ='Bakeacake'
if password == 'Bakeacake':
    print('Access granted.')
else:
    print('Wrong password!')

name = 'Bob'
age = 3000
if name == "Alice":
  print('Hi bae!')
elif age < 12:
  print('You are not Alice, kiddo.')
elif age > 2000:
  print('Alice is not you, vampire.')
elif age > 100:
  print('You are not Alice, grannie,')

print('Enter a name:')
name = input()
if name != "":
  print('Thank you for entering a name.')
else:
  print('You did not enter a name.')

spam = 0
while spam < 5:
  print('Hello World!')
  spam = spam + 1

name = ''
while name != 'your name':
  print('Please type your name.')
  name = input()
print('Thank you!')

name = ''
while True:
  print('Please type your name.')
  name = input()
  if name == 'your name':
    break
print('Thank you!')

spam = 0
while spam < 5:
  spam = spam + 1
  if spam == 3:
    continue
  print('spam is ' + str(spam))

print('My name is')
for i in range(5):
  print ('Jimmy Five Times ' + str(i))

total = 0
for num in range (101):
  total = total + num
print (total)

a=4
b=7
print(a)
print("Thanh")
print("hello")