# -*- coding: utf-8 -*-
"""Automate the boring Stuff with Python chap 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Wlz2UeweK9jzuHUuB4kFItBhGpyWJj8
"""

spam = ['cat', 'bat', 'rat', 'elephant']
print(spam[0])
print(spam[-1])
print(spam[1:3])


spam = 'Hello'
spam = [10, 20, 30]
spam[1] = 'Hello'
spam
spam[1:3] = ['CAT', 'DOG', 'MOUSE']
spam

spam = ['cat', 'bat', 'rat', 'elephant']
spam[:2]
spam[1:]

spam = ['cat', 'bat', 'rat', 'elephant']
del spam[2]
spam

len([1,2,3])

[1,2,3] + [4,5,6]

[1,2,3] * 3

list('Hello')

'howdy' in ['hello', 'hi','howdy']

42 not in ['hello', 'hi','howdy']

list(range(4))

list(range(0, 100, 2))

supplies = ['pens', 'staplers', 'flame-throwers', 'binders']
for i in range(len(supplies)):
  print('Index ' + str(i) + ' in supplies is: ' + supplies[i])

cat = ['fat', 'orange', 'loud']
size, color, disposition = cat
print(size)

size, color, disposition = 'skinny', 'black', 'quiet'
print(size)

a = 'AAA'
b = 'BBB'
a, b = b, a
print(a,b)

"""spam = spam + 1   == spam += 1

"""

spam = ['hello', 'hi', 'howdy']
spam.index('hi')

spam = ['Sophie', 'Fooka', 'Fat-tail', 'Fooka']
spam.index('Fooka')

spam = ['cat', 'dog', 'bat']
spam.append('moose')
spam.insert(1, 'chicken')
spam.remove('bat')
print(spam)

spam = [2, 5, 3.14, 1, -7]
spam.sort()
print(spam)

"""Can also sort string in alphabetical order
(upper key before lower key)
"""

spam = ['A', 'Z', 'a', 'z']
spam.sort(key=str.lower)
print(spam)

spam = [2, 5, 3.14, 1, -7]
spam.sort(reverse=True)
print(spam)

"""Mutable data: List (can be modified by remove, append,...)
Imutable data: String (cannot be modified)
--> CHANGE STRING BY USING SLICES.
The difference between immutable and mutable comes up with "references".

"""

name = 'Zophie a cat'
newName = name[0:7] + 'the' + name[8:12]
print(newName)

spam = [0, 1, 2, 3, 4, 5]
cheese = spam
cheese[1] = 'Hello'
print(spam)
print(cheese)

"""Mutable data store references instead of the variables themselves."""

def eggs(cheese):
  cheese.append('Hello')

spam = [1, 2, 3]
eggs(spam)
print(spam)

"""Why the local data can change the global data in this case? (change in references save)"""

import copy

spam = ['A', 'B','C','D']
cheese = copy.deepcopy(spam)
print(cheese)

cheese[1] = 42
print(cheese)
print(spam)

"""Indentation does not affect the code when listing."""

print('Four score and seven ' + \
       'years ago.')