# -*- coding: utf-8 -*-
"""Automate the Boring Stuff with Python chap 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1POqGlADn0VpZK5Fy5ulMWCwQWX5pF5ns
"""

#This program says hello and asks for my name
print('Hello World!')
print('What is your name?') #ask for their name
myName = input()
print('It it good to meet you, ' + myName)
print('The length of your name is: ' + str(len(myName)))
print('What is your age?') #ask for their age
myAge = input()
print('You will be ' + str(int(myAge)+ 1) + ' in a year.')