# -*- coding: utf-8 -*-
"""Automate the Boring Stuff with Python chap 8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NeReG0I_qg1XE6VrNHMAqHNw_LRS5dim
"""

"That's Alice's cat"
'Say hi to Bob\'s mother'
print('Hello!\nHow are you?')
r'That Carol\'s cat.'
print(r'That Carol\'s cat.')

print("""Dear Alice,
Eve's cat has been arrested.
Love, Bob.""")

spam = 'Hello World!'
spam.upper()
print(spam.upper())
spam.lower()
print(spam.lower())

spam = 'Hello World!'
spam.islower()

'Hello'.upper()
'Hello'.upper().isupper()

'Hello World!'.startswith('H')

'Hello World!'.endswith('world!')

'! '.join(['cats', 'rats', 'bats'])

'My name is K'.split()

'My name is Simmone.'.split('m')

'Hello'.rjust(10,'*')

'Hello'.center(20,'-')

'Hello'.rjust(10,)
spam = 'Hello'.rjust(10)
spam.strip()

'SpamSpamBaconSpamEggsSpamSpam'.strip('ampS')

spam = 'Hello there!'
spam.replace('e','XYZ')

name = 'Alice'
place = 'Main Street'
time = '6PM'
food = 'carrots'
'Hello %s, you are invited to a party at %s at %s. Please bring %s' %(name, place, time, food)