# -*- coding: utf-8 -*-
"""Automate the Boring Stuff with Python chap 7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TbbDX5KSBs1ylNn-6ndoTch_MyK6Qji7
"""

myCat = {'size': 'fat', 'color': 'gray', 'disposition': 'loud'}
myCat['size']
print('My cat has ' + myCat['color'] +  ' fur.')

[1, 2, 3] == [3, 2, 1]

eggs = {'name': 'Zophie', 'species': 'cat', 'age': 8}
ham = {'species': 'cat', 'name': 'Zophie', 'age': 8}
eggs == ham

eggs = {'name': 'Zophie', 'species': 'cat', 'age': 8}
'name' in eggs

eggs = {'name': 'Zophie', 'species': 'cat', 'age': 8}

list(eggs.keys())
list(eggs.values())
list(eggs.items())

eggs = {'name': 'Zophie', 'species': 'cat', 'age': 8}
for k in eggs.keys():
  print(k)
for v in eggs.values():
  print(v)
for a, b in eggs.items():
  print(a, b)

eggs = {'name': 'Zophie', 'species': 'cat', 'age': 8}
eggs.get('age', 0)

eggs = {'name': 'Zophie', 'species': 'cat', 'age': 8}
eggs.setdefault('color', 'black')
print(eggs)

import pprint

message = 'It was a bright cold day in April, and the clocks were striking thirteen.'
count = {}
for character in message:
  count.setdefault(character, 0)
  count[character] += 1
pprint.pprint(count)
text = pprint.pformat(count)
print(text)

theBoard = {'top-L': ' ', 'top-M': ' ', 'top-R': ' ', 'mid-L': ' ', 'mid-M': ' ', 'mid-R': ' ', 'low-L': ' ', 'low-M': ' ', 'low-R': ' ',}
import pprint
pprint.pprint(theBoard)

def printBoard(board):
  print(board['top-L'] + '|' + board['top-M'] + '|' + board['top-R'])
  print('-----')
  print(board['mid-L'] + '|' + board['mid-M'] + '|' + board['mid-R'])
  print('-----')
  print(board['low-L'] + '|' + board['low-M'] + '|' + board['low-R'])


print(printBoard(theBoard))

type(42)
type(3.14)
type('hello')

print(7 % 7)
print(7 % 2)

print(7 // 7)
print(7 // 2)