# -*- coding: utf-8 -*-
"""Chap 10.1 - Phone and email

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vc1emW2YqdWt9dZKX_0kTs-URYOVkw4x
"""

#! python3

import re
# TODO: Create a regex for phone numbers
phoneRegex = re.compile(r'''
(
((\d\d\d)|(\(\d\d\d\))?)   #area code (optional)
(\s|-)                    #first separator
\d\d\d                    #first 3 digits
-                         #separator
\d\d\d\d                  #last 4 digits
(((ext(\.)?\s)|x)         #extension word-part (option)
(\d{2,5}))?               #extension number-part (option)
)
''', re.VERBOSE)
#TODO: Create a regex for emails
emailRegex = re.compile(r'''
#some.+_thing@(\d{2,5})?.com
[a-zA-Z0-9_.+]+     #name part
@                   #@ symbol
[a-zA-Z0-9_.+]+     #domain name part
''', re.VERBOSE)
#Get text
text = input()
#TODO: Extract the email/phone from this text
extractedPhone = phoneRegex.findall(text)
extractedEmail = emailRegex.findall(text)

allPhoneNumbers = []
for phoneNumber in extractedPhone:
  allPhoneNumbers.append(phoneNumber[0])

results = '\n'.join(allPhoneNumbers) + '\n' + '\n'.join(extractedEmail)
print(results)

